apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vegeta
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      containers:
      - name: vegeta
        image: vishnunair/docker-vegeta
